seq = "ATGCTGCTCCTGTTCCTCCTCTTCGAGGGTCTCTGCTGTCCTGGGGAAAATACAGCAGTG" \
      "AAGCCAGAGGCCTGGCTGTCCTGTGGCCCCAGTCCTGGCCCTGGCCGTCTGCAGCTTGTG" \
      "TGCCATGTCTCAGGATTCTACCCAAAGCCCGTGTGGGTGATGTGGATGCGGGGTGGATAT" \
      "TCCATCTTTCTCATCCTGATCTGTTTGACTGTGATAGTTACCCTGGTCATATTGGTTGTA" \
      "GTTGACTCACGGTTAAAAAAACAGAGCCCTGTCTTTCTCATGGGAGCCAACACTCAGGAC" \
      "ACCAAGAATTCAAGACATCAGTTCTGCTTGGCACAAGTATCGTGGATCAAAAACAGAGTA" \
      "TTGAAGAAGTGGAAGACACGCCTAAACCAACTCTGGTGA"


print("Последовательность целиком:")
print(seq)
print() 

print("Последовательность построчно:")
for i in range(0, len(seq), 50):
    print(seq[i:i+50])

print()  
print("Цикл выполнен")